hibernate.driver_class = org.postgresql.Driver
hibernate.connection.url = jdbc:postgresql://localhost:5432/spleproyekassoc_product_zaruman
hibernate.connection.username = postgres
hibernate.connection.password = postgres
hibernate.hbm2ddl.auto = update
hibernate.dialect = org.hibernate.dialect.PostgreSQL94Dialect
hibernate.show_sql = false